# action.yml
name: 'DependencyTrack check SBOM'
description: 'Creating SBOM and upload to DependencyTrack'
inputs:
  url:
    description: 'Dtrack URL REST API'
    required: true
    default: 'http://localhost:8080/'
  key:
    description: 'Dtrack KEY REST API'
    required: true
    default: ${{ secrets.DTKEY }}
outputs:
  riskscore:
    description: 'Vulnerabilities INFO'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.key }}
