
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      
      - name: Creating SBOM and upload to DependencyTrack
        id: riskscore
        uses:  R-dado/SBOM-Dependency-Track-Check@main
        with:
          url: 'http://localhost:8080/'
          key: '${{ secrets.DTKEY }}'
      
      - name: riskscore output
        run: echo "Riskscore is ${{ steps.riskscore.outputs.riskscore }}"
